version: "3.8"
services:
  db:
    image: mariadb:11
    container_name: flags-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: flags
      MARIADB_USER: app
      MARIADB_PASSWORD: app
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: flags-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data: {}
  redis_data: {}
