spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.hibernate.SQL: info
    com.myapp.ffs.segment: info    # 운영에선 디버그 로그 끔

app:
  cache:
    log-hit: false
  segment:
    log-eval: false
