spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Seoul
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/html,text/xml,text/plain
    min-response-size: 1024

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: feature-flag-service

# 공통 기본 로그 레벨(세부는 각 프로필에서 오버라이드)
logging:
  level:
    org.springframework.data.redis.connection: info
    org.springframework.data.redis.core: info

# 앱 내부 토글 키 이름 통일 (log-eval)
app:
  cache:
    log-hit: false       # 기본값: 비활성
  segment:
    log-eval: false      # 기본값: 비활성
