spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/flags
    username: app
    password: app
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: Asia/Seoul
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/html,text/xml,text/plain
    min-response-size: 1024

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.data.redis.connection: info
    org.springframework.data.redis.core: info

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

