name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Test (with REST Docs snippets)
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew clean test

      - name: Generate REST Docs HTML
        if: always()
        run: ./gradlew asciidoctor || true

      - name: Archive REST Docs snippets
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rest-docs-snippets
          path: |
            build/generated-snippets/**

      - name: Archive Asciidoctor docs (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rest-docs-html
          path: |
            build/docs/asciidoc/**
